name: t3-v14-1
type: typo3
docroot: public
php_version: "8.3"
webserver_type: nginx-fpm
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
  type: mariadb
  version: "10.11"
nodejs_version: "20"
corepack_enable: true

# Performance
mutagen_enabled: false
nfs_mount_enabled: false

# Hooks
hooks:
  post-start:
    - exec: composer install

# Web Environment
web_environment:
  - TYPO3_CONTEXT=Development
  - TYPO3_DB_DRIVER=mysqli
  - TYPO3_DB_HOST=db
  - TYPO3_DB_PORT=3306
  - TYPO3_DB_NAME=db
  - TYPO3_DB_USER=db
  - TYPO3_DB_PASSWORD=db
